/**
 * mixingPresets.js
 * ─────────────────
 * Ready-to-use professional mixing & mastering presets for Jagat Audio DAW.
 */

export const TRACK_MIXING_PRESETS = [
  {
    category: 'Vocal',
    presets: [
      {
        id: 'vocal_crisp',
        name: 'Lead Vocal Crisp & Bright',
        desc: 'Vokal utama jernih, bright, kompresi rapat & airy reverb',
        effects: {
          gate: { enabled: true, threshold: -48 },
          lowCut: { enabled: true, frequency: 100 },
          saturation: { enabled: true, drive: 0.15, warmth: 0.4 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: -2.0, mid: 1.5, high: 4.0 },
          compressor: { enabled: true, threshold: -20, ratio: 4, attack: 0.005, release: 0.2 },
          chorus: { enabled: false, wet: 0.2, depth: 0.4, rate: 1.2 },
          delay: { enabled: true, wet: 0.12, feedback: 0.25 },
          reverb: { enabled: true, wet: 0.28, decay: 2.2 },
        },
      },
      {
        id: 'vocal_warm_radio',
        name: 'Warm Radio Broadcast',
        desc: 'Suara podcast/radio hangat, tebal di midrange, kompresi solid',
        effects: {
          gate: { enabled: true, threshold: -45 },
          lowCut: { enabled: true, frequency: 80 },
          saturation: { enabled: true, drive: 0.35, warmth: 0.75 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: 2.5, mid: 2.0, high: 1.0 },
          compressor: { enabled: true, threshold: -18, ratio: 5, attack: 0.003, release: 0.15 },
          chorus: { enabled: false, wet: 0.2, depth: 0.4, rate: 1.2 },
          delay: { enabled: false, wet: 0.1, feedback: 0.2 },
          reverb: { enabled: true, wet: 0.1, decay: 1.0 },
        },
      },
      {
        id: 'vocal_dream_airy',
        name: 'Airy Dream Pop Vocal',
        desc: 'Vokal lebar dengan stereo chorus doubler & reverb atmosferik',
        effects: {
          gate: { enabled: true, threshold: -50 },
          lowCut: { enabled: true, frequency: 120 },
          saturation: { enabled: false, drive: 0.2, warmth: 0.5 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: -3.0, mid: 0.5, high: 5.0 },
          compressor: { enabled: true, threshold: -22, ratio: 3.5, attack: 0.01, release: 0.3 },
          chorus: { enabled: true, wet: 0.4, depth: 0.65, rate: 1.0 },
          delay: { enabled: true, wet: 0.25, feedback: 0.4 },
          reverb: { enabled: true, wet: 0.45, decay: 3.8 },
        },
      },
      {
        id: 'vocal_lofi',
        name: 'Vintage Lo-Fi Telephone',
        desc: 'Efek vokal telepon jadul retro dengan midrange sempit & distorsi halus',
        effects: {
          gate: { enabled: false, threshold: -50 },
          lowCut: { enabled: true, frequency: 380 },
          saturation: { enabled: true, drive: 0.55, warmth: 0.9 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: -12.0, mid: 6.0, high: -8.0 },
          compressor: { enabled: true, threshold: -15, ratio: 8, attack: 0.002, release: 0.1 },
          chorus: { enabled: false, wet: 0.2, depth: 0.4, rate: 1.2 },
          delay: { enabled: true, wet: 0.15, feedback: 0.3 },
          reverb: { enabled: true, wet: 0.15, decay: 1.2 },
        },
      },
    ],
  },
  {
    category: 'Drums & Perkusi',
    presets: [
      {
        id: 'drum_punchy_kick',
        name: 'Punchy Heavy Kick',
        desc: 'Kick drum nendang dengan sub bass bertenaga & noise gate ketat',
        effects: {
          gate: { enabled: true, threshold: -38 },
          lowCut: { enabled: true, frequency: 30 },
          saturation: { enabled: true, drive: 0.25, warmth: 0.6 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: 5.0, mid: -4.0, high: 2.0 },
          compressor: { enabled: true, threshold: -16, ratio: 5.5, attack: 0.02, release: 0.1 },
          chorus: { enabled: false, wet: 0, depth: 0, rate: 1 },
          delay: { enabled: false, wet: 0, feedback: 0 },
          reverb: { enabled: false, wet: 0.05, decay: 0.8 },
        },
      },
      {
        id: 'drum_snappy_snare',
        name: 'Snappy Crack Snare',
        desc: 'Snare renyah berkarakter dengan mid punch & gated reverb',
        effects: {
          gate: { enabled: true, threshold: -40 },
          lowCut: { enabled: true, frequency: 90 },
          saturation: { enabled: true, drive: 0.2, warmth: 0.5 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: -1.0, mid: 3.5, high: 3.0 },
          compressor: { enabled: true, threshold: -18, ratio: 4, attack: 0.008, release: 0.15 },
          chorus: { enabled: false, wet: 0, depth: 0, rate: 1 },
          delay: { enabled: false, wet: 0, feedback: 0 },
          reverb: { enabled: true, wet: 0.22, decay: 1.4 },
        },
      },
      {
        id: 'drum_modern_bus',
        name: 'Modern Full Drum Bus',
        desc: 'Menyatukan seluruh track drum dengan kompresi lem dan ruangan alami',
        effects: {
          gate: { enabled: false, threshold: -50 },
          lowCut: { enabled: true, frequency: 35 },
          saturation: { enabled: true, drive: 0.2, warmth: 0.5 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: 2.5, mid: -1.0, high: 2.5 },
          compressor: { enabled: true, threshold: -18, ratio: 3.5, attack: 0.015, release: 0.2 },
          chorus: { enabled: false, wet: 0, depth: 0, rate: 1 },
          delay: { enabled: false, wet: 0, feedback: 0 },
          reverb: { enabled: true, wet: 0.14, decay: 1.6 },
        },
      },
    ],
  },
  {
    category: 'Bass',
    presets: [
      {
        id: 'bass_fat_sub',
        name: 'Fat Sub & Warm Bass',
        desc: 'Bass tebal bertenaga untuk Pop, R&B, dan Dangdut Modern',
        effects: {
          gate: { enabled: false, threshold: -50 },
          lowCut: { enabled: true, frequency: 30 },
          saturation: { enabled: true, drive: 0.35, warmth: 0.8 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: 5.5, mid: -2.0, high: -3.5 },
          compressor: { enabled: true, threshold: -20, ratio: 5, attack: 0.01, release: 0.25 },
          chorus: { enabled: false, wet: 0, depth: 0, rate: 1 },
          delay: { enabled: false, wet: 0, feedback: 0 },
          reverb: { enabled: false, wet: 0, decay: 1.0 },
        },
      },
      {
        id: 'bass_rock_pick',
        name: 'Punchy Rock Pick Bass',
        desc: 'Bass petikan tegas dengan overdrive gurih dan midrange menonjol',
        effects: {
          gate: { enabled: true, threshold: -45 },
          lowCut: { enabled: true, frequency: 45 },
          saturation: { enabled: true, drive: 0.45, warmth: 0.7 },
          guitar: { enabled: true, mode: 'overdrive', drive: 0.35 },
          eq: { low: 2.0, mid: 4.0, high: 1.5 },
          compressor: { enabled: true, threshold: -16, ratio: 4.5, attack: 0.005, release: 0.18 },
          chorus: { enabled: false, wet: 0, depth: 0, rate: 1 },
          delay: { enabled: false, wet: 0, feedback: 0 },
          reverb: { enabled: false, wet: 0.05, decay: 0.8 },
        },
      },
    ],
  },
  {
    category: 'Gitar & Akustik',
    presets: [
      {
        id: 'guitar_acoustic_shimmer',
        name: 'Acoustic Guitar Shimmer',
        desc: 'Gitar akustik renyah berkilau dengan stereo chorus & reverb luas',
        effects: {
          gate: { enabled: false, threshold: -50 },
          lowCut: { enabled: true, frequency: 90 },
          saturation: { enabled: false, drive: 0.1, warmth: 0.3 },
          guitar: { enabled: false, mode: 'clean', drive: 0.5 },
          eq: { low: -2.0, mid: 1.0, high: 4.5 },
          compressor: { enabled: true, threshold: -22, ratio: 3, attack: 0.012, release: 0.2 },
          chorus: { enabled: true, wet: 0.3, depth: 0.5, rate: 1.2 },
          delay: { enabled: true, wet: 0.15, feedback: 0.25 },
          reverb: { enabled: true, wet: 0.32, decay: 2.4 },
        },
      },
      {
        id: 'guitar_clean_funk',
        name: 'Clean Funk Rhythm',
        desc: 'Petikan elektrik bersih, dinamis, kompresi cepat ala funk & jazz',
        effects: {
          gate: { enabled: true, threshold: -48 },
          lowCut: { enabled: true, frequency: 80 },
          saturation: { enabled: true, drive: 0.15, warmth: 0.4 },
          guitar: { enabled: true, mode: 'clean', drive: 0.2 },
          eq: { low: -1.0, mid: 2.5, high: 3.0 },
          compressor: { enabled: true, threshold: -20, ratio: 4.5, attack: 0.003, release: 0.12 },
          chorus: { enabled: true, wet: 0.25, depth: 0.45, rate: 1.8 },
          delay: { enabled: false, wet: 0.1, feedback: 0.2 },
          reverb: { enabled: true, wet: 0.18, decay: 1.5 },
        },
      },
      {
        id: 'guitar_lead_crunch',
        name: 'Heavy Rock Lead Crunch',
        desc: 'Solo gitar rock dengan distorsi bertenaga & delay solo tebal',
        effects: {
          gate: { enabled: true, threshold: -40 },
          lowCut: { enabled: true, frequency: 80 },
          saturation: { enabled: true, drive: 0.6, warmth: 0.8 },
          guitar: { enabled: true, mode: 'distortion', drive: 0.7 },
          eq: { low: 1.0, mid: 3.5, high: 2.0 },
          compressor: { enabled: true, threshold: -18, ratio: 4, attack: 0.005, release: 0.2 },
          chorus: { enabled: false, wet: 0.2, depth: 0.4, rate: 1.2 },
          delay: { enabled: true, wet: 0.3, feedback: 0.45 },
          reverb: { enabled: true, wet: 0.25, decay: 2.0 },
        },
      },
    ],
  },
];

export const MASTERING_PRESETS = [
  {
    id: 'master_streaming_lufs',
    name: '⚡ Streaming Loudness Target (-14 LUFS)',
    desc: 'Standar mastering optimal untuk YouTube, Spotify, TikTok tanpa distorsi',
    suite: {
      eq: { low: 1.0, mid: 0.5, high: 1.8, subCut: true },
      compressor: { enabled: true, threshold: -14, ratio: 2.5, attack: 0.03, release: 0.2 },
      width: 1.1,
      isMono: false,
      limiter: { enabled: true, ceiling: -0.5 },
    },
  },
  {
    id: 'master_warm_analog',
    name: '📻 Warm Analog Tape Master',
    desc: 'Karakter rekaman pita analog vintage, bass tebal dan nada halus',
    suite: {
      eq: { low: 2.5, mid: 1.0, high: -0.5, subCut: true },
      compressor: { enabled: true, threshold: -16, ratio: 3.0, attack: 0.04, release: 0.3 },
      width: 1.0,
      isMono: false,
      limiter: { enabled: true, ceiling: -0.3 },
    },
  },
  {
    id: 'master_club_bass',
    name: '🔊 Club / EDM Bass Heavy',
    desc: 'Punch bass maksimal untuk speaker sound system dan panggung',
    suite: {
      eq: { low: 3.5, mid: -0.8, high: 2.2, subCut: true },
      compressor: { enabled: true, threshold: -12, ratio: 3.5, attack: 0.02, release: 0.15 },
      width: 1.25,
      isMono: false,
      limiter: { enabled: true, ceiling: -0.2 },
    },
  },
  {
    id: 'master_acoustic_clarity',
    name: '🌿 Acoustic & Jazz Clarity Master',
    desc: 'Dinamika natural, transparan, dan ruang stereo 3D yang sangat luas',
    suite: {
      eq: { low: 0.0, mid: 0.8, high: 2.5, subCut: true },
      compressor: { enabled: true, threshold: -18, ratio: 1.8, attack: 0.05, release: 0.4 },
      width: 1.35,
      isMono: false,
      limiter: { enabled: true, ceiling: -0.8 },
    },
  },
];
